=begin
#V4 Online API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v4

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

require 'spec_helper'
require 'json'

# Unit tests for RentCentric::QuoteApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'QuoteApi' do
  before do
    # run before each test
    @instance = RentCentric::QuoteApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of QuoteApi' do
    it 'should create an instance of QuoteApi' do
      expect(@instance).to be_instance_of(RentCentric::QuoteApi)
    end
  end

  # unit tests for quote_get_quote_calculate
  # @param request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization {token_type} {access_token}
  # @return [ResponseQuoteCalculateDTO]
  describe 'quote_get_quote_calculate test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
