=begin
#V4 Online API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v4

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

require 'spec_helper'
require 'json'

# Unit tests for RentCentric::RentalApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'RentalApi' do
  before do
    # run before each test
    @instance = RentCentric::RentalApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RentalApi' do
    it 'should create an instance of RentalApi' do
      expect(@instance).to be_instance_of(RentCentric::RentalApi)
    end
  end

  # unit tests for rental_get_number_of_rentals
  # @param location_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization {token_type} {access_token}
  # @return [ResponseNumberOfRentalsDTO]
  describe 'rental_get_number_of_rentals test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for rental_get_rentals
  # @param request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization {token_type} {access_token}
  # @return [ResponseListRentalDto]
  describe 'rental_get_rentals test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
