=begin
#V4 Online API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v4

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

require 'spec_helper'
require 'json'

# Unit tests for RentCentric::ReservationApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReservationApi' do
  before do
    # run before each test
    @instance = RentCentric::ReservationApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReservationApi' do
    it 'should create an instance of ReservationApi' do
      expect(@instance).to be_instance_of(RentCentric::ReservationApi)
    end
  end

  # unit tests for reservation_get_active_reservation
  # @param customer_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization {token_type} {access_token}
  # @return [ResponseGetActiveReservationResponse]
  describe 'reservation_get_active_reservation test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for reservation_get_number_of_reservations
  # @param location_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization {token_type} {access_token}
  # @return [ResponseNumberOfReservationsDTO]
  describe 'reservation_get_number_of_reservations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for reservation_get_reservations
  # @param request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization {token_type} {access_token}
  # @return [ResponseListReservationDto]
  describe 'reservation_get_reservations test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
