=begin
#V4 Online API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v4

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

require 'spec_helper'
require 'json'

# Unit tests for RentCentric::SelfServiceApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'SelfServiceApi' do
  before do
    # run before each test
    @instance = RentCentric::SelfServiceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SelfServiceApi' do
    it 'should create an instance of SelfServiceApi' do
      expect(@instance).to be_instance_of(RentCentric::SelfServiceApi)
    end
  end

  # unit tests for self_service_get_member_ship_package
  # @param location_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization {token_type} {access_token}
  # @return [ResponseListMemberShipTypeDTO]
  describe 'self_service_get_member_ship_package test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for self_service_get_registration_polices
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization {token_type} {access_token}
  # @return [ResponseString]
  describe 'self_service_get_registration_polices test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
