=begin
#V4 Online API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v4

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

require 'spec_helper'
require 'json'

# Unit tests for RentCentric::VehicleApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VehicleApi' do
  before do
    # run before each test
    @instance = RentCentric::VehicleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VehicleApi' do
    it 'should create an instance of VehicleApi' do
      expect(@instance).to be_instance_of(RentCentric::VehicleApi)
    end
  end

  # unit tests for vehicle_get_available_vehicles
  # @param request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization {token_type} {access_token}
  # @return [ResponseListVehicleDTO]
  describe 'vehicle_get_available_vehicles test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for vehicle_get_available_vehicles_search_criteria
  # @param request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization {token_type} {access_token}
  # @return [ResponseAvailableVehiclesSearchCriteriaDTO]
  describe 'vehicle_get_available_vehicles_search_criteria test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for vehicle_get_locations_by_available_vehicles
  # @param request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization {token_type} {access_token}
  # @return [ResponseListGetLocationsByAvailableVehiclesDTO]
  describe 'vehicle_get_locations_by_available_vehicles test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for vehicle_get_vehicle
  # @param vehicle_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization {token_type} {access_token}
  # @return [ResponseVehicleDTO]
  describe 'vehicle_get_vehicle test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for vehicle_get_vehicle_calendar
  # @param request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization {token_type} {access_token}
  # @return [ResponseGetVehicleCalendarResponse]
  describe 'vehicle_get_vehicle_calendar test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for vehicle_get_vehicles
  # @param pickup_location_id 
  # @param vehicle_type_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization {token_type} {access_token}
  # @return [ResponseListVehicleDTO]
  describe 'vehicle_get_vehicles test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
