=begin
#V4 Online API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v4

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

require 'spec_helper'
require 'json'

# Unit tests for RentCentric::VehicleTypeApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VehicleTypeApi' do
  before do
    # run before each test
    @instance = RentCentric::VehicleTypeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VehicleTypeApi' do
    it 'should create an instance of VehicleTypeApi' do
      expect(@instance).to be_instance_of(RentCentric::VehicleTypeApi)
    end
  end

  # unit tests for vehicle_type_get_all_vehicle_types
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization {token_type} {access_token}
  # @return [ResponseListVehicleTypesResponse]
  describe 'vehicle_type_get_all_vehicle_types test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for vehicle_type_get_available_vehicle_types_and_rates
  # @param request 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :authorization {token_type} {access_token}
  # @return [ResponseListAvailableVehicleTypesAndRatesDTO]
  describe 'vehicle_type_get_available_vehicle_types_and_rates test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
