=begin
#V4 Online API

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: v4

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.15

=end

# Common files
require 'rent_centric/api_client'
require 'rent_centric/api_error'
require 'rent_centric/version'
require 'rent_centric/configuration'

# Models
require 'rent_centric/models/admin_login_request'
require 'rent_centric/models/admin_login_response'
require 'rent_centric/models/available_vehicle_types_and_rates_dto'
require 'rent_centric/models/available_vehicles_search_criteria_dto'
require 'rent_centric/models/available_vehicles_with_rate_dto'
require 'rent_centric/models/charge_summary_dto'
require 'rent_centric/models/company_dto'
require 'rent_centric/models/country_dto'
require 'rent_centric/models/customer_credit_card_dto_response'
require 'rent_centric/models/customer_dto_response'
require 'rent_centric/models/customer_membership_package_info_dto'
require 'rent_centric/models/customer_scanned_i_ds_dto'
require 'rent_centric/models/get_active_reservation_response'
require 'rent_centric/models/get_add_ons_one_list_response'
require 'rent_centric/models/get_add_ons_requset'
require 'rent_centric/models/get_add_ons_response'
require 'rent_centric/models/get_available_vehicle_type_and_rates_request'
require 'rent_centric/models/get_available_vehicles_request'
require 'rent_centric/models/get_available_vehicles_search_criteria_request'
require 'rent_centric/models/get_customer_response'
require 'rent_centric/models/get_customers_request'
require 'rent_centric/models/get_insurance_request'
require 'rent_centric/models/get_locations_by_available_vehicles_dto'
require 'rent_centric/models/get_locations_by_available_vehicles_request'
require 'rent_centric/models/get_misc_charge_request'
require 'rent_centric/models/get_quote_calculate_request'
require 'rent_centric/models/get_rentals_request'
require 'rent_centric/models/get_reported_damage_request'
require 'rent_centric/models/get_reservations_request'
require 'rent_centric/models/get_tax_request'
require 'rent_centric/models/get_vehicle_calendar_request'
require 'rent_centric/models/get_vehicle_calendar_response'
require 'rent_centric/models/insurance_dto'
require 'rent_centric/models/insurance_types_dto'
require 'rent_centric/models/location_dto'
require 'rent_centric/models/location_public_setting_dto'
require 'rent_centric/models/make_model_dto'
require 'rent_centric/models/map_point'
require 'rent_centric/models/member_ship_type_dto'
require 'rent_centric/models/misc_charge_dto'
require 'rent_centric/models/mobile_app_version_dto'
require 'rent_centric/models/number_of_rentals_dto'
require 'rent_centric/models/number_of_reservations_dto'
require 'rent_centric/models/one_way_location'
require 'rent_centric/models/option_group_dto'
require 'rent_centric/models/pay_method_dto'
require 'rent_centric/models/quote_calculate_charge'
require 'rent_centric/models/quote_calculate_dto'
require 'rent_centric/models/quote_calculate_option'
require 'rent_centric/models/rate_values'
require 'rent_centric/models/rental_dto'
require 'rent_centric/models/reported_damage_dto'
require 'rent_centric/models/reservation_dto'
require 'rent_centric/models/response_admin_login_response'
require 'rent_centric/models/response_available_vehicles_search_criteria_dto'
require 'rent_centric/models/response_boolean'
require 'rent_centric/models/response_customer_credit_card_dto_response'
require 'rent_centric/models/response_date_time'
require 'rent_centric/models/response_get_active_reservation_response'
require 'rent_centric/models/response_get_customer_response'
require 'rent_centric/models/response_get_vehicle_calendar_response'
require 'rent_centric/models/response_int32'
require 'rent_centric/models/response_list_available_vehicle_types_and_rates_dto'
require 'rent_centric/models/response_list_company_dto'
require 'rent_centric/models/response_list_country_dto'
require 'rent_centric/models/response_list_get_add_ons_one_list_response'
require 'rent_centric/models/response_list_get_add_ons_response'
require 'rent_centric/models/response_list_get_customer_response'
require 'rent_centric/models/response_list_get_locations_by_available_vehicles_dto'
require 'rent_centric/models/response_list_insurance_dto'
require 'rent_centric/models/response_list_insurance_types_dto'
require 'rent_centric/models/response_list_location_dto'
require 'rent_centric/models/response_list_member_ship_type_dto'
require 'rent_centric/models/response_list_misc_charge_dto'
require 'rent_centric/models/response_list_one_way_location'
require 'rent_centric/models/response_list_pay_method_dto'
require 'rent_centric/models/response_list_rental_dto'
require 'rent_centric/models/response_list_reported_damage_dto'
require 'rent_centric/models/response_list_reservation_dto'
require 'rent_centric/models/response_list_state_dto'
require 'rent_centric/models/response_list_tax_dto'
require 'rent_centric/models/response_list_vehicle_dto'
require 'rent_centric/models/response_list_vehicle_types_response'
require 'rent_centric/models/response_location_dto'
require 'rent_centric/models/response_location_public_setting_dto'
require 'rent_centric/models/response_map_point'
require 'rent_centric/models/response_mobile_app_version_dto'
require 'rent_centric/models/response_number_of_rentals_dto'
require 'rent_centric/models/response_number_of_reservations_dto'
require 'rent_centric/models/response_quote_calculate_dto'
require 'rent_centric/models/response_self_service_car_rental_setup_dto'
require 'rent_centric/models/response_string'
require 'rent_centric/models/response_vehicle_dto'
require 'rent_centric/models/self_service_car_rental_setup_dto'
require 'rent_centric/models/state_dto'
require 'rent_centric/models/tax_dto'
require 'rent_centric/models/vehicle_dto'
require 'rent_centric/models/vehicle_type_dto'
require 'rent_centric/models/vehicle_types_response'

# APIs
require 'rent_centric/api/company_api'
require 'rent_centric/api/customer_api'
require 'rent_centric/api/damage_api'
require 'rent_centric/api/gps_control_api'
require 'rent_centric/api/location_api'
require 'rent_centric/api/quote_api'
require 'rent_centric/api/rate_api'
require 'rent_centric/api/rental_api'
require 'rent_centric/api/reservation_api'
require 'rent_centric/api/self_service_api'
require 'rent_centric/api/setting_api'
require 'rent_centric/api/token_api'
require 'rent_centric/api/vehicle_api'
require 'rent_centric/api/vehicle_type_api'

module RentCentric
  class << self
    # Customize default settings for the SDK using block.
    #   RentCentric.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
